version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    networks:
      - ingress-pool
      - default
    command: 
      #- "--log.level=DEBUG"
      - "--providers.docker.defaultRule=Host(`\
        {{ index .Labels \"com.docker.compose.service\"}}.\
        {{ index .Labels \"com.docker.compose.project\"}}.\
        ${ROOT_DOMAIN}`)"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.constraints=Label(`traefik.http.routers.whoami.rule`,``)"
      - "--providers.docker.network=ingress-pool"
    ports:
      - "80:80"
      - "8580:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "./traefik:/etc/traefik/"
networks:
  ingress-pool:
    name: ingress-pool
#    driver: bridge
    attachable: true
