api:
  insecure: true
  dashboard: true
  debug: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ .Name }}.ingress.localhost`)"
    exposedByDefault: false
    network: ingress-pool
entryPoints:
  web:
    address: ":80"
log:
  level: INFO